# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1335477059);
user_pref("app.update.lastUpdateTime.background-update-timer", 1335477057);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1335477057);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1335477059);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1335477060);
user_pref("browser.migration.version", 1);
user_pref("browser.places.createdSmartBookmarks", true);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.importDefaults", false);
user_pref("browser.places.leftPaneFolderId", -1);
user_pref("browser.places.migratePostDataAnnotations", false);
user_pref("browser.places.updateRecentTagsUri", false);
user_pref("browser.startup.homepage_override.mstone", "rv:1.9b5");
user_pref("extensions.enabledItems", "langpack-he@firefox.mozilla.org:3.0b5,langpack-es-AR@firefox.mozilla.org:3.0b5,langpack-zh-CN@firefox.mozilla.org:3.0b5,langpack-ko@firefox.mozilla.org:3.0b5,langpack-af@firefox.mozilla.org:3.0b5,langpack-uk@firefox.mozilla.org:3.0b5,langpack-id@firefox.mozilla.org:3.0b5,langpack-ar@firefox.mozilla.org:3.0b5,langpack-es-ES@firefox.mozilla.org:3.0b5,langpack-pt-BR@firefox.mozilla.org:3.0b5,langpack-nb-NO@firefox.mozilla.org:3.0b5,langpack-gu-IN@firefox.mozilla.org:3.0b5,langpack-pl@firefox.mozilla.org:3.0b5,langpack-fr@firefox.mozilla.org:3.0b5,langpack-en-GB@firefox.mozilla.org:3.0b5,langpack-sk@firefox.mozilla.org:3.0b5,langpack-ka@firefox.mozilla.org:3.0b5,langpack-ru@firefox.mozilla.org:3.0b5,langpack-mn@firefox.mozilla.org:3.0b5,langpack-zh-TW@firefox.mozilla.org:3.0b5,langpack-ku@firefox.mozilla.org:3.0b5,langpack-ro@firefox.mozilla.org:3.0b5,langpack-nl@firefox.mozilla.org:3.0b5,langpack-pt-PT@firefox.mozilla.org:3.0b5,langpack-fi@firefox.mozilla.org:3.0b5,langpack-de@firefox.mozilla.org:3.0b5,langpack-cs@firefox.mozilla.org:3.0b5,langpack-eu@firefox.mozilla.org:3.0b5,langpack-ja@firefox.mozilla.org:3.0b5,langpack-el@firefox.mozilla.org:3.0b5,langpack-nn-NO@firefox.mozilla.org:3.0b5,langpack-da@firefox.mozilla.org:3.0b5,langpack-it@firefox.mozilla.org:3.0b5,langpack-be@firefox.mozilla.org:3.0b5,langpack-hu@firefox.mozilla.org:3.0b5,langpack-fy-NL@firefox.mozilla.org:3.0b5,langpack-tr@firefox.mozilla.org:3.0b5,langpack-ca@firefox.mozilla.org:3.0b5,langpack-lt@firefox.mozilla.org:3.0b5,langpack-sr@firefox.mozilla.org:3.0b5,langpack-sv-SE@firefox.mozilla.org:3.0b5,langpack-pa-IN@firefox.mozilla.org:3.0b5,{972ce4c6-7e08-4474-a285-3208198ce6fd}:2.0");
user_pref("extensions.lastAppVersion", "3.0b5");
user_pref("intl.charsetmenu.browser.cache", "us-ascii, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1338069062);
